### ISSUE TITLE
Set a licence on garment creation and show it in garment page

### ISSUE THREAD

**Issue by Bramvanosta** [ecvdbdx1617/github-for-fashion#53]
At the moment, it is not possible to get the licence of a Github repo from the API without adding the "preview" flag ([Github API Guide](https://developer.github.com/v3/licenses/).

The github-api JS library we use does not allow to add this custom flag to the API request.

In the future we will be able to use the native licence mechanism from the Github API, for now we need to include it in the config file.

**Comment by DavidBruant** [comment]
On creation, the garment maker should be able to set a licence. Choices are the 6 licences listed in https://creativecommons.org/licenses/ + `CC0` https://creativecommons.org/share-your-work/public-domain/cc0/ + `none` (no licence, "all rights reserved").
For now, let's say the default should be CC-BY.
When giving the choice, add links to the various licence texts so the garment maker is clearly informed about the choice they make.

Save the chosen licence somehow.

On display, show the chosen licence.
