### ISSUE TITLE
As a logged in user, I want to post a garment project

### ISSUE THREAD

**Issue by simon-milleto** [ecvdbdx1617/github-for-fashion#6]
I want to be able to contribute : 

- Picture of the result
- The type of garment
- The size of the garment
- The licence of the project
- Technical description of the garment
- Category of the garment
- The state of the project (Completed, ongoing...)
- Garment composition list
- Pattern files

**Comment by DavidBruant** [comment]
Done enough for now. Create new issue if changes are necessary
